theme: theme
title: Overview
author: Jason Morley
email: support@jbmorley.co.uk
description: Calendar Summaries
baseurl: ""
url: "https://overview.jbmorley.co.uk"
repository: https://github.com/inseven/overview
copyright: 2021-2025 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Overview
    href: /
  - title: Releases
    href: /releases
  - title: GitHub
    href: https://github.com/inseven/overview
  - title: Donate
    href: https://jbmorley.co.uk/support/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: Support
    href: /support
  - title: License
    href: /license
  - title: More Software
    href: https://jbmorley.co.uk/software/

plugins:
  - jekyll-feed
  - jekyll-environment-variables
  - jekyll-toc
  - jekyll-image-size
destination: ../_site

defaults:
  - values:
      layout: "page"
